// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupportTicketSysterm.Data;

#nullable disable

namespace SupportTicketSysterm.Migrations
{
    [DbContext(typeof(TechSupportContext))]
    [Migration("20260717091148_AddOtpVerificationTable")]
    partial class AddOtpVerificationTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SupportTicketSysterm.Data.DanhGium", b =>
                {
                    b.Property<int>("IdDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDanhGia"));

                    b.Property<int?>("ChatLuongDichVu")
                        .HasColumnType("int");

                    b.Property<int?>("IdNhanVienPhanHoi")
                        .HasColumnType("int");

                    b.Property<int?>("IdPhieu")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("NgayPhanHoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanXet")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PhanHoiNhanVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ThaiDoNhanVien")
                        .HasColumnType("int");

                    b.Property<int?>("TocDoXuLy")
                        .HasColumnType("int");

                    b.HasKey("IdDanhGia")
                        .HasName("PK__DanhGia__81F722D23D384ECE");

                    b.HasIndex("IdNhanVienPhanHoi");

                    b.HasIndex(new[] { "IdPhieu" }, "UQ__DanhGia__48C313843604E870")
                        .IsUnique()
                        .HasFilter("[IdPhieu] IS NOT NULL");

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("SupportTicketSysterm.Data.DanhMuc", b =>
                {
                    b.Property<int>("IdDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDanhMuc"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdDanhMuc")
                        .HasName("PK__DanhMuc__7E5B713D86F9EB57");

                    b.ToTable("DanhMuc", (string)null);
                });

            modelBuilder.Entity("SupportTicketSysterm.Data.DichVu", b =>
                {
                    b.Property<int>("IdDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDichVu"));

                    b.Property<int>("IdDanhMuc")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdDichVu")
                        .HasName("PK__DichVu__C817D5DC49787F5A");

                    b.HasIndex("IdDanhMuc");

                    b.ToTable("DichVu", (string)null);
                });

            modelBuilder.Entity("SupportTicketSysterm.Data.FileDinhKem", b =>
                {
                    b.Property<int>("IdFile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFile"));

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("IdDanhGia")
                        .HasColumnType("int");

                    b.Property<int?>("IdPhieu")
                        .HasColumnType("int");

                    b.Property<int?>("IdTinNhan")
                        .HasColumnType("int");

                    b.Property<string>("LoaiFile")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayUpload")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TenFile")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdFile")
                        .HasName("PK__FileDinh__01E644E13B84DED7");

                    b.HasIndex("IdDanhGia");

                    b.HasIndex("IdPhieu");

                    b.HasIndex("IdTinNhan");

                    b.ToTable("FileDinhKem", (string)null);
                });

            modelBuilder.Entity("SupportTicketSysterm.Data.KhachHang", b =>
                {
                    b.Property<int>("IdKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKhachHang"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaKh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MaKH");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayTao")
                        .HasColumnType("date");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdKhachHang")
                        .HasName("PK__KhachHan__7CF5D836A178D854");

                    b.HasIndex(new[] { "Email" }, "UQ__KhachHan__A9D10534C8FE3D65")
                        .IsUnique()
                        .HasFilter("([Email] IS NOT NULL)");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("SupportTicketSysterm.Data.LichHen", b =>
                {
                    b.Property<int>("IdLichHen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLichHen"));

                    b.Property<string>("DiaChiHoTro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeOnly?>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<int?>("IdNhanVien")
                        .HasColumnType("int");

                    b.Property<int?>("IdPhieu")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgayHen")
                        .HasColumnType("date");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdLichHen")
                        .HasName("PK__LichHen__C7CECEDC30600A2F");

                    b.HasIndex("IdNhanVien");

                    b.HasIndex("IdPhieu");

                    b.ToTable("LichHen", (string)null);
                });

            modelBuilder.Entity("SupportTicketSysterm.Data.LichSuHoTro", b =>
                {
                    b.Property<int>("IdLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLichSu"));

                    b.Property<int?>("IdNhanVien")
                        .HasColumnType("int");

                    b.Property<int?>("IdPhieu")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgayCapNhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiDungCapNhat")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TrangThaiCu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThaiMoi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdLichSu")
                        .HasName("PK__LichSuHo__823B17725F23BBB5");

                    b.HasIndex("IdNhanVien");

                    b.HasIndex("IdPhieu");

                    b.ToTable("LichSuHoTro", (string)null);
                });

            modelBuilder.Entity("SupportTicketSysterm.Data.LichSuHoatDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IdKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("IdNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThucHien")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdNhanVien");

                    b.ToTable("LichSuHoatDong");
                });

            modelBuilder.Entity("SupportTicketSysterm.Data.LienHe", b =>
                {
                    b.Property<int>("IdLienHe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLienHe"));

                    b.Property<int?>("IdKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("IdNhanVien")
                        .HasColumnType("int");

                    b.Property<int?>("IdPhieu")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgayTao")
                        .HasColumnType("date");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoTinChuaDoc")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianGui")
                        .HasColumnType("datetime");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("TinChuaDocKhach")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdLienHe")
                        .HasName("PK__LienHe__03AC912A65747A5D");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdNhanVien");

                    b.HasIndex("IdPhieu");

                    b.ToTable("LienHe", (string)null);
                });

            modelBuilder.Entity("SupportTicketSysterm.Data.NhanVien", b =>
                {
                    b.Property<int>("IdNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNhanVien"));

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaNhanVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdNhanVien")
                        .HasName("PK__NhanVien__B829484532AC2146");

                    b.HasIndex(new[] { "TenDangNhap" }, "UQ__NhanVien__55F68FC08DF75591")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__NhanVien__A9D10534C79D90BE")
                        .IsUnique();

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("SupportTicketSysterm.Data.OtpVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("OtpCodeHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("OtpVerification", (string)null);
                });

            modelBuilder.Entity("SupportTicketSysterm.Data.PhieuHoTro", b =>
                {
                    b.Property<int>("IdPhieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPhieu"));

                    b.Property<string>("CanLichHen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("IdDichVu")
                        .HasColumnType("int");

                    b.Property<int?>("IdKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("IdNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("LoaiYeuCau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaPhieu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("MucDoUuTien")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgayCapNhat")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdPhieu")
                        .HasName("PK__PhieuHoT__48C313854EE11F2E");

                    b.HasIndex("IdDichVu");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdNhanVien");

                    b.HasIndex(new[] { "MaPhieu" }, "UQ__PhieuHoT__2660BFE1A2B28B08")
                        .IsUnique();

                    b.ToTable("PhieuHoTro", (string)null);
                });

            modelBuilder.Entity("SupportTicketSysterm.Data.TaiKhoanOtp", b =>
                {
                    b.Property<int>("IdOtp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdOTP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOtp"));

                    b.Property<DateTime>("HanSuDung")
                        .HasColumnType("datetime");

                    b.Property<int>("IdKhachHang")
                        .HasColumnType("int");

                    b.Property<string>("Otp")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("OTP");

                    b.HasKey("IdOtp")
                        .HasName("PK__TaiKhoan__2A0AD5FD0DE7C3F3");

                    b.HasIndex("IdKhachHang");

                    b.ToTable("TaiKhoan_OTP", (string)null);
                });

            modelBuilder.Entity("SupportTicketSysterm.Data.TinNhan", b =>
                {
                    b.Property<int>("IdTinNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTinNhan"));

                    b.Property<int?>("IdLienHe")
                        .HasColumnType("int");

                    b.Property<string>("LoaiNguoiGui")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ThoiGian")
                        .HasColumnType("datetime");

                    b.Property<string>("TinNhan1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TinNhan");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTinNhan")
                        .HasName("PK__TinNhan__C1329D0D9C4927D0");

                    b.HasIndex("IdLienHe");

                    b.ToTable("TinNhan", (string)null);
                });

            modelBuilder.Entity("SupportTicketSysterm.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdKhachHang")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("SupportTicketSysterm.Data.DanhGium", b =>
                {
                    b.HasOne("SupportTicketSysterm.Data.NhanVien", "IdNhanVienPhanHoiNavigation")
                        .WithMany()
                        .HasForeignKey("IdNhanVienPhanHoi");

                    b.HasOne("SupportTicketSysterm.Data.PhieuHoTro", "IdPhieuNavigation")
                        .WithOne("DanhGium")
                        .HasForeignKey("SupportTicketSysterm.Data.DanhGium", "IdPhieu")
                        .HasConstraintName("FK__DanhGia__IdPhieu__66603565");

                    b.Navigation("IdNhanVienPhanHoiNavigation");

                    b.Navigation("IdPhieuNavigation");
                });

            modelBuilder.Entity("SupportTicketSysterm.Data.DichVu", b =>
                {
                    b.HasOne("SupportTicketSysterm.Data.DanhMuc", "IdDanhMucNavigation")
                        .WithMany("DichVus")
                        .HasForeignKey("IdDanhMuc")
                        .IsRequired()
                        .HasConstraintName("FK__DichVu__IdDanhMu__47DBAE45");

                    b.Navigation("IdDanhMucNavigation");
                });

            modelBuilder.Entity("SupportTicketSysterm.Data.FileDinhKem", b =>
                {
                    b.HasOne("SupportTicketSysterm.Data.DanhGium", "IdDanhGiaNavigation")
                        .WithMany("FileDinhKems")
                        .HasForeignKey("IdDanhGia")
                        .HasConstraintName("FK__FileDinhK__IdDan__6B24EA82");

                    b.HasOne("SupportTicketSysterm.Data.PhieuHoTro", "IdPhieuNavigation")
                        .WithMany("FileDinhKems")
                        .HasForeignKey("IdPhieu")
                        .HasConstraintName("FK__FileDinhK__IdPhi__6A30C649");

                    b.HasOne("SupportTicketSysterm.Data.TinNhan", "IdTinNhanNavigation")
                        .WithMany("FileDinhKems")
                        .HasForeignKey("IdTinNhan")
                        .HasConstraintName("FK__FileDinhK__IdTin__6C190EBB");

                    b.Navigation("IdDanhGiaNavigation");

                    b.Navigation("IdPhieuNavigation");

                    b.Navigation("IdTinNhanNavigation");
                });

            modelBuilder.Entity("SupportTicketSysterm.Data.LichHen", b =>
                {
                    b.HasOne("SupportTicketSysterm.Data.NhanVien", "IdNhanVienNavigation")
                        .WithMany("LichHens")
                        .HasForeignKey("IdNhanVien")
                        .HasConstraintName("FK__LichHen__IdNhanV__5DCAEF64");

                    b.HasOne("SupportTicketSysterm.Data.PhieuHoTro", "IdPhieuNavigation")
                        .WithMany("LichHens")
                        .HasForeignKey("IdPhieu")
                        .HasConstraintName("FK__LichHen__IdPhieu__5EBF139D");

                    b.Navigation("IdNhanVienNavigation");

                    b.Navigation("IdPhieuNavigation");
                });

            modelBuilder.Entity("SupportTicketSysterm.Data.LichSuHoTro", b =>
                {
                    b.HasOne("SupportTicketSysterm.Data.NhanVien", "IdNhanVienNavigation")
                        .WithMany("LichSuHoTros")
                        .HasForeignKey("IdNhanVien")
                        .HasConstraintName("FK__LichSuHoT__IdNha__5441852A");

                    b.HasOne("SupportTicketSysterm.Data.PhieuHoTro", "IdPhieuNavigation")
                        .WithMany("LichSuHoTros")
                        .HasForeignKey("IdPhieu")
                        .HasConstraintName("FK__LichSuHoT__IdPhi__534D60F1");

                    b.Navigation("IdNhanVienNavigation");

                    b.Navigation("IdPhieuNavigation");
                });

            modelBuilder.Entity("SupportTicketSysterm.Data.LichSuHoatDong", b =>
                {
                    b.HasOne("SupportTicketSysterm.Data.KhachHang", "IdKhachHangNavigation")
                        .WithMany()
                        .HasForeignKey("IdKhachHang");

                    b.HasOne("SupportTicketSysterm.Data.NhanVien", "IdNhanVienNavigation")
                        .WithMany("LichSuHoatDongs")
                        .HasForeignKey("IdNhanVien");

                    b.Navigation("IdKhachHangNavigation");

                    b.Navigation("IdNhanVienNavigation");
                });

            modelBuilder.Entity("SupportTicketSysterm.Data.LienHe", b =>
                {
                    b.HasOne("SupportTicketSysterm.Data.KhachHang", "IdKhachHangNavigation")
                        .WithMany("LienHes")
                        .HasForeignKey("IdKhachHang")
                        .HasConstraintName("FK__LienHe__IdKhachH__571DF1D5");

                    b.HasOne("SupportTicketSysterm.Data.NhanVien", "IdNhanVienNavigation")
                        .WithMany("LienHes")
                        .HasForeignKey("IdNhanVien")
                        .HasConstraintName("FK__LienHe__IdNhanVi__5812160E");

                    b.HasOne("SupportTicketSysterm.Data.PhieuHoTro", "IdPhieuNavigation")
                        .WithMany()
                        .HasForeignKey("IdPhieu")
                        .HasConstraintName("FK_LienHe_PhieuHoTro");

                    b.Navigation("IdKhachHangNavigation");

                    b.Navigation("IdNhanVienNavigation");

                    b.Navigation("IdPhieuNavigation");
                });

            modelBuilder.Entity("SupportTicketSysterm.Data.PhieuHoTro", b =>
                {
                    b.HasOne("SupportTicketSysterm.Data.DichVu", "IdDichVuNavigation")
                        .WithMany("PhieuHoTros")
                        .HasForeignKey("IdDichVu")
                        .HasConstraintName("FK__PhieuHoTr__IdDic__4F7CD00D");

                    b.HasOne("SupportTicketSysterm.Data.KhachHang", "IdKhachHangNavigation")
                        .WithMany("PhieuHoTros")
                        .HasForeignKey("IdKhachHang")
                        .HasConstraintName("FK__PhieuHoTr__IdKha__4D94879B");

                    b.HasOne("SupportTicketSysterm.Data.NhanVien", "IdNhanVienNavigation")
                        .WithMany("PhieuHoTros")
                        .HasForeignKey("IdNhanVien")
                        .HasConstraintName("FK__PhieuHoTr__IdNha__4E88ABD4");

                    b.Navigation("IdDichVuNavigation");

                    b.Navigation("IdKhachHangNavigation");

                    b.Navigation("IdNhanVienNavigation");
                });

            modelBuilder.Entity("SupportTicketSysterm.Data.TaiKhoanOtp", b =>
                {
                    b.HasOne("SupportTicketSysterm.Data.KhachHang", "IdKhachHangNavigation")
                        .WithMany("TaiKhoanOtps")
                        .HasForeignKey("IdKhachHang")
                        .IsRequired()
                        .HasConstraintName("FK_OTP_KhachHang");

                    b.Navigation("IdKhachHangNavigation");
                });

            modelBuilder.Entity("SupportTicketSysterm.Data.TinNhan", b =>
                {
                    b.HasOne("SupportTicketSysterm.Data.LienHe", "IdLienHeNavigation")
                        .WithMany("TinNhans")
                        .HasForeignKey("IdLienHe")
                        .HasConstraintName("FK__TinNhan__IdLienH__5AEE82B9");

                    b.Navigation("IdLienHeNavigation");
                });

            modelBuilder.Entity("SupportTicketSysterm.Data.DanhGium", b =>
                {
                    b.Navigation("FileDinhKems");
                });

            modelBuilder.Entity("SupportTicketSysterm.Data.DanhMuc", b =>
                {
                    b.Navigation("DichVus");
                });

            modelBuilder.Entity("SupportTicketSysterm.Data.DichVu", b =>
                {
                    b.Navigation("PhieuHoTros");
                });

            modelBuilder.Entity("SupportTicketSysterm.Data.KhachHang", b =>
                {
                    b.Navigation("LienHes");

                    b.Navigation("PhieuHoTros");

                    b.Navigation("TaiKhoanOtps");
                });

            modelBuilder.Entity("SupportTicketSysterm.Data.LienHe", b =>
                {
                    b.Navigation("TinNhans");
                });

            modelBuilder.Entity("SupportTicketSysterm.Data.NhanVien", b =>
                {
                    b.Navigation("LichHens");

                    b.Navigation("LichSuHoTros");

                    b.Navigation("LichSuHoatDongs");

                    b.Navigation("LienHes");

                    b.Navigation("PhieuHoTros");
                });

            modelBuilder.Entity("SupportTicketSysterm.Data.PhieuHoTro", b =>
                {
                    b.Navigation("DanhGium");

                    b.Navigation("FileDinhKems");

                    b.Navigation("LichHens");

                    b.Navigation("LichSuHoTros");
                });

            modelBuilder.Entity("SupportTicketSysterm.Data.TinNhan", b =>
                {
                    b.Navigation("FileDinhKems");
                });
#pragma warning restore 612, 618
        }
    }
}
